workspace(name = "examples")

local_repository(name = "io_bazel_rules_rust", path = "..")

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories()

new_git_repository(
    name = "libc",
    remote = "https://github.com/rust-lang/libc",
    tag = "0.2.20",
    build_file = "libc.BUILD",
)

load("@io_bazel_rules_rust//proto:repositories.bzl", "rust_proto_repositories")
rust_proto_repositories()
